# Weight V3  Datset V1
#python detect.py --cfg cfg/polyp_train_yolov4-pacsp.cfg --names data/polyp.names --weights weights/best_yolov4-pacsp_v3.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v1/EndoCV_DATA1/ --img-size 640 --conf-thres 0.01 --iou-thres 0.1 --device 0 --save-txt
#python detect.py --cfg cfg/polyp_train_yolov4-pacsp.cfg --names data/polyp.names --weights weights/best_yolov4-pacsp_v3.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v1/EndoCV_DATA2/ --img-size 640 --conf-thres 0.01 --iou-thres 0.1 --device 0 --save-txt
#python detect.py --cfg cfg/polyp_train_yolov4-pacsp.cfg --names data/polyp.names --weights weights/best_yolov4-pacsp_v3.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v1/EndoCV_DATA3/ --img-size 640 --conf-thres 0.01 --iou-thres 0.1 --device 0 --save-txt
# Weight V3  Datset V2
#python detect.py --cfg cfg/polyp_train_yolov4-pacsp.cfg --names data/polyp.names --weights weights/best_yolov4-pacsp_v3.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA1/ --img-size 640 --conf-thres 0.01 --iou-thres 0.1 --device 0 --save-txt
#python detect.py --cfg cfg/polyp_train_yolov4-pacsp.cfg --names data/polyp.names --weights weights/best_yolov4-pacsp_v3.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA2/ --img-size 640 --conf-thres 0.01 --iou-thres 0.1 --device 0 --save-txt
#python detect.py --cfg cfg/polyp_train_yolov4-pacsp.cfg --names data/polyp.names --weights weights/best_yolov4-pacsp_v3.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA3/ --img-size 640 --conf-thres 0.01 --iou-thres 0.1 --device 0 --save-txt
# Weight V4  Datset V2
#python detect.py --cfg cfg/polyp_train_yolov4-pacspcbam.cfg --names data/polyp.names --weights weights/best_yolov4-pacspcbam.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA1/ --img-size 640 --conf-thres 0.001 --iou-thres 0.01 --device cpu --save-txt
#python detect.py --cfg cfg/polyp_train_yolov4-pacspcbam.cfg --names data/polyp.names --weights weights/best_yolov4-pacspcbam.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA2/ --img-size 640 --conf-thres 0.001 --iou-thres 0.01 --device cpu --save-txt
#python detect.py --cfg cfg/polyp_train_yolov4-pacspcbam.cfg --names data/polyp.names --weights weights/best_yolov4-pacspcbam.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA3/ --img-size 640 --conf-thres 0.001 --iou-thres 0.01 --device cpu --save-txt
# Weight V5  Datset V2
#python detect.py --cfg cfg/polyp_train_yolov4-pacspcbam_v2.cfg --names data/polyp.names --weights weights/best_yolov4-pacspcbam_v2.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA1/ --img-size 640 --conf-thres 0.001 --iou-thres 0.01 --device cpu --save-txt
#python detect.py --cfg cfg/polyp_train_yolov4-pacspcbam_v2.cfg --names data/polyp.names --weights weights/best_yolov4-pacspcbam_v2.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA2/ --img-size 640 --conf-thres 0.001 --iou-thres 0.01 --device cpu --save-txt
python detect.py --cfg cfg/polyp_train_yolov4-pacspcbam_v2.cfg --names data/polyp.names --weights weights/best_yolov4-pacspcbam_v2.pt --source /project/def-sponsor00/endocv2021-test-noCopyAllowed-v2/EndoCV_DATA3/ --img-size 640 --conf-thres 0.001 --iou-thres 0.01 --device cpu --save-txt
